    <div class="content">
        <header>
            <h1>Array Básico</h1>
        </header>

        <h3>O que são Arrays?</h3>
        <p>
            Arrays são listas ordenadas. Basicamente falando Arrays são variáveis que é pertmitido
            relacionar itens associados a índices. Este tipo de array tenta imitar a lista do mundo real.
        </p>
    
    
        <div id='content'>
            <div class="div">
                <h3>Com variáveis:</h3>
                <ul>
                    <li>
                        $variavel_1 = 'Banana'
                    </li>
                    <li>
                        $variavel_1 = 'Maça'
                    </li>
                    <li>
                        $variavel_1 = 'Laranja'
                    </li>
                    <li>
                        $variavel_1 = 'Uva'
                    </li>
                </ul>
            </div>
            
            <div class="div" id="div2">
                <h3>Com array:</h3>
                <ul>
                    <li>
                        $lista_frutas[1] = 'Banana'
                    </li>
                    <li>
                        $lista_frutas[2] = 'Maça'
                    </li>
                    <li>
                        $lista_frutas[3] = 'Laranja'
                    </li>
                    <li>
                        $lista_frutas[4] = 'Uva'
                    </li>
                </ul>
            </div>
        </div>

    </div>

